//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.GLSL {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMS.GLSL.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die radians degrees 
        ///sin cos tan 
        ///asin acos atan
        ///sinh cosh tanh 
        ///asinh acosh atanh 
        ///pow exp log exp2 log2 
        ///sqrt inversesqrt
        ///abs sign floor trunc round roundEven ceil fract mod modf
        ///min max clamp mix step smoothstep
        ///isnan isinf
        ///floatBitsToInt floatBitsToUint 
        ///intBitsToFloat uintBitsToFloat
        ///fma frexp ldexp
        ///packUnorm2x16 packSnorm2x16 packUnorm4x8 packSnorm4x8 
        ///unpackUnorm2x16 unpackSnorm2x16 unpackUnorm4x8 unpackSnorm4x8 
        ///packDouble2x32
        ///unpackDouble2x32
        ///packHalf2x16
        ///unpackHalf2x16
        ///length distan [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string glslFunctions {
            get {
                return ResourceManager.GetString("glslFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die attribute const
        ///uniform   varying    buffer    shared
        ///coherent    volatile    restrict    readonly    writeonly
        ///atomic_uint
        ///layout
        ///centroid    flat    smooth    noperspective
        ///patch    sample
        ///break   continue   do   for   while    switch    case    default 
        ///if    else
        ///subroutine
        ///in   out   
        ///inout
        ///float   double    int   void   
        ///bool
        ///true  false
        ///invariant    precise
        ///discard   return
        ///mat2  mat3  mat4                  dmat2  dmat3  dmat4
        ///mat2x2   mat2x3   mat2x4    dmat2x2   dmat2x3   dmat2x4        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string glslKeywords {
            get {
                return ResourceManager.GetString("glslKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gl_NumWorkGroups
        ///gl_WorkGroupSize
        ///gl_WorkGroupID
        ///gl_LocalInvocationID
        ///gl_GlobalInvocationID
        ///gl_LocalInvocationIndex
        ///
        ///gl_VertexID
        ///gl_InstanceID
        ///gl_PerVertex
        ///gl_Position
        ///gl_PointSize
        ///gl_ClipDistance
        ///gl_CullDistance
        ///gl_in
        ///
        ///gl_PrimitiveIDIn
        ///gl_InvocationID
        ///
        ///gl_PrimitiveID
        ///gl_Layer
        ///gl_ViewportIndex
        ///
        ///gl_PatchVerticesIn
        ///gl_PrimitiveID
        ///gl_InvocationID
        ///
        ///gl_TessLevelOuter
        ///gl_TessLevelInner
        ///
        ///gl_PatchVerticesIn
        ///gl_PrimitiveID
        ///gl_TessCoord
        ///
        ///gl_FragColor
        ///gl_FragCoord
        ///gl_FrontFacing
        ///gl [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string glslVariables {
            get {
                return ResourceManager.GetString("glslVariables", resourceCulture);
            }
        }
    }
}
